name: Coverage
on: ["push", "pull_request"]

jobs:
  build:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Gather coverage
        run:
          echo -n '${{ secrets.BEEVENUE_CI_PR_BUILD_CONFIG }}' > src/config.ts &&
          npm install && npm test -- --coverage --watchAll=false
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
