name: PR build
on:
  workflow_dispatch:
  push:
    branches:
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Build
        run:
          echo -n '${{ secrets.BEEVENUE_CI_PR_BUILD_CONFIG }}' > src/config.json &&
          npm install && npm run build
